import { User, Post, Listing, Community, Story, Notification } from './types';

// Avatars
export const currentUser: User = {
  id: 'me',
  name: 'Nousheen Faizan',
  handle: 'nousheen_f',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  coverImage: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=1000&auto=format&fit=crop&q=80',
  bio: 'Digital experiences designer & high-velocity tech enthusiast. Custom styling every pixel in 2026. 💻✨',
  followers: 1240,
  following: 482,
  verified: true,
  isMe: true,
};

export const sampleUsers: Record<string, User> = {
  maya_zen: {
    id: 'user_maya',
    name: 'Maya Zen',
    handle: 'mayazen',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    followers: 14200,
    following: 110,
    verified: true,
  },
  alex_rivera: {
    id: 'user_alex',
    name: 'Alex Rivera',
    handle: 'alex_r',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    followers: 8400,
    following: 320,
    verified: true,
  },
  jamie_l: {
    id: 'user_jamie',
    name: 'Jamie L.',
    handle: 'jamie_l',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    followers: 3200,
    following: 450,
    verified: false,
  },
  sarah_j: {
    id: 'user_sarah',
    name: 'Sarah Jenkins',
    handle: 'sarah_jenkins',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    followers: 18900,
    following: 890,
    verified: true,
  },
  marcus_r: {
    id: 'user_marcus',
    name: 'Marcus Reed',
    handle: 'marcus_reed',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    followers: 9210,
    following: 1120,
    verified: false,
  },
  daniel_chen: {
    id: 'user_daniel',
    name: 'Daniel Chen',
    handle: 'dan_chen',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    followers: 24500,
    following: 95,
    verified: true,
  },
  julian_thorne: {
    id: 'user_julian',
    name: 'Julian Thorne',
    handle: 'julian_t',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    followers: 43200,
    following: 154,
    verified: true,
  },
  maya_sterling: {
    id: 'user_maya_s',
    name: 'Maya Sterling',
    handle: 'maya_sterling',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    followers: 15200,
    following: 231,
    verified: true,
  },
};

// Stories Data
export const sampleStories: Story[] = [
  {
    id: 'story_own',
    author: currentUser,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80',
    viewed: false,
  },
  {
    id: 'story_alex',
    author: sampleUsers.alex_rivera,
    image: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=500&auto=format&fit=crop&q=80',
    viewed: false,
  },
  {
    id: 'story_jamie',
    author: sampleUsers.jamie_l,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=500&auto=format&fit=crop&q=80',
    viewed: false,
  },
  {
    id: 'story_sarah',
    author: sampleUsers.sarah_j,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop&q=80',
    viewed: true,
  },
  {
    id: 'story_marcus',
    author: sampleUsers.marcus_r,
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=500&auto=format&fit=crop&q=80',
    viewed: true,
  },
];

// Posts Feed Data
export const initialPosts: Post[] = [
  {
    id: 'post_maya_zen',
    author: sampleUsers.maya_zen,
    content: 'Just dropped the new 2026 motion collection! 🌈 Every piece is designed to flow with the rhythm of the city. Which vibe are you feeling today?',
    images: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80'],
    likes: 14200,
    timestamp: '2h ago',
    tag: 'Featured Creator',
    likedByMe: false,
    shares: 48,
    comments: [
      {
        id: 'c1',
        author: sampleUsers.alex_rivera,
        content: 'Unbelievable workflow! The fluidity is insane.',
        timestamp: '1h ago',
      },
      {
        id: 'c2',
        author: sampleUsers.jamie_l,
        content: 'Need to learn this rendering technique ASAP!',
        timestamp: '30m ago',
      },
    ],
  },
  {
    id: 'post_julian',
    author: sampleUsers.julian_thorne,
    content: 'The future of collaborative interfaces is looking brighter than ever. Exploring new ways to bring teams together in the 2026 design landscape. ✨',
    images: ['https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80'],
    likes: 1200,
    timestamp: '2h ago',
    location: 'Silicon Valley, CA',
    likedByMe: true,
    shares: 12,
    comments: [
      {
        id: 'c3',
        author: sampleUsers.maya_zen,
        content: 'This feels incredibly tactile! Perfect layered composition.',
        timestamp: '1h ago',
      },
    ],
  },
  {
    id: 'post_daniel',
    author: sampleUsers.daniel_chen,
    content: 'Coffee and morning code. Finally finished the latest interface update! 💻☕',
    images: [
      'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517134191118-9d595e4c8c2b?w=600&auto=format&fit=crop&q=80'
    ],
    likes: 1210,
    timestamp: '5h ago',
    location: 'Brooklyn, NY',
    likedByMe: false,
    shares: 18,
    comments: [
      {
        id: 'c4',
        author: sampleUsers.marcus_r,
        content: 'Amazing split layout setup. Coffee looks top tier!',
        timestamp: '4h ago',
      },
    ],
  },
  {
    id: 'post_maya_sterling',
    author: sampleUsers.maya_sterling,
    content: 'Finally made it to the coast! The architecture here is simply breathtaking. Can\'t wait to show you the full tour tomorrow. 🌊🏛️',
    images: [
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=600&auto=format&fit=crop&q=80'
    ],
    likes: 842,
    timestamp: '4h ago',
    location: 'Malibu, CA',
    likedByMe: false,
    shares: 5,
    comments: [
      {
        id: 'c5',
        author: currentUser,
        content: 'Those white walls contrast so beautifully with the ocean! Post coordinates please.',
        timestamp: '3h ago',
      },
    ],
  },
];

// Communities Data
export const sampleCommunities: Community[] = [
  {
    id: 'c_tech',
    name: 'Keeb Enthusiasts',
    category: 'TECH & GEAR',
    membersCount: '12k Active Now',
    activeCount: '2.4k online',
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=500&auto=format&fit=crop&q=80',
    joined: false,
    description: 'Custom mechanical keyboard builds, retro caps, switch lubing techniques, and pristine desk setups.',
  },
  {
    id: 'c_life',
    name: 'Urban Jungle',
    category: 'LIFESTYLE',
    membersCount: '45k Members',
    activeCount: '1.2k online',
    image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=500&auto=format&fit=crop&q=80',
    joined: false,
    description: 'Sharing advice, tips, and inspiration on urban houseplant care, fiddle leaf figs, and propagation guides.',
  },
  {
    id: 'c_design',
    name: '2026 UI Motion',
    category: 'DESIGN ARCH',
    membersCount: '8.4k Members',
    activeCount: '450 online',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=500&auto=format&fit=crop&q=80',
    joined: true,
    description: 'Interactive high-fidelity motion prototypes, micro-transitions, web animations, and glassmorphism styling.',
  },
  {
    id: 'c_gaming',
    name: 'Retro Arcade Devs',
    category: 'GAMING EXPO',
    membersCount: '14.2k Members',
    activeCount: '890 online',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=80',
    joined: false,
    description: 'Pixel art creators, game mechanics designers, and arcade cabin restorers, pushing the boundary of nostalgia.',
  },
];

// Marketplace Data (Today's Picks)
export const initialListings: Listing[] = [
  {
    id: 'list_tesla',
    title: '2022 Tesla Model 3 Long Range',
    price: 32500,
    category: 'Vehicles',
    location: 'San Francisco, CA',
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80',
    description: 'Pristine condition, single owner, AWD dual-motor Long Range. 35,000 miles, clean title, garage kept. Premium white interior upgrade, Full Self-Driving capabilities prepaid.',
    likes: 312,
    likedByMe: false,
    status: 'active',
    seller: sampleUsers.alex_rivera,
    timestamp: '1d ago',
  },
  {
    id: 'list_chair',
    title: 'Eames Style Lounge Chair & Ottoman',
    price: 850,
    category: 'Home',
    location: 'Oakland, CA',
    image: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800&auto=format&fit=crop&q=80',
    description: 'High-quality reproduction with premium Italian leather and walnut plywood shells. Incredible condition, very minor scuffs on metal feet base. Extremely comfortable!',
    likes: 195,
    likedByMe: true,
    status: 'active',
    seller: sampleUsers.maya_zen,
    timestamp: '2d ago',
  },
  {
    id: 'list_macbook',
    title: 'MacBook Pro M3 Max (16", 48GB, 1TB)',
    price: 1800,
    category: 'Electronics',
    location: 'San Jose, CA',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Supercharged 16-inch Space Black MacBook. 14-Core CPU, 30-Core GPU, 48GB unified memory, and 1TB SSD. Original box and Apple MagSafe USB-C charger included. Battery health 98%.',
    likes: 450,
    likedByMe: false,
    status: 'active',
    seller: sampleUsers.daniel_chen,
    timestamp: '5h ago',
  },
  {
    id: 'list_fig',
    title: 'Large Healthy Fiddle Leaf Fig',
    price: 45,
    category: 'Home',
    location: 'Berkeley, CA',
    image: 'https://images.unsplash.com/photo-1597055181300-e3633a207518?w=800&auto=format&fit=crop&q=80',
    description: 'Beautiful 6-foot-tall indoor plant. Thick, glossy leaves, very robust and healthy. Comes in custom white ceramic pot. Perfect statement piece for high-light modern living rooms.',
    likes: 28,
    likedByMe: false,
    status: 'active',
    seller: sampleUsers.maya_sterling,
    timestamp: '3d ago',
  },
  {
    id: 'list_shoes',
    title: 'Brand New Designer Sneakers (Size 10)',
    price: 210,
    category: 'Apparel',
    location: 'Marin, CA',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80',
    description: 'Minimalist platform sneakers. Premium calfskin leather, cloud-cushioned interior, stylish grey rear tab details. Never worn, original packaging, dustbags, and extra laces included.',
    likes: 84,
    likedByMe: false,
    status: 'active',
    seller: sampleUsers.jamie_l,
    timestamp: '1w ago',
  },
  {
    id: 'list_bike',
    title: 'Specialized Carbon Road Bike (54cm)',
    price: 2400,
    category: 'Vehicles',
    location: 'Palo Alto, CA',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop&q=80',
    description: 'Ultralight FACT 11r carbon fiber frame, completely optimized with Shimano Ultegra Di2 electronic shifting. Hydraulic disc brakes, lightweight carbon tubeless-ready wheelset.',
    likes: 129,
    likedByMe: false,
    status: 'active',
    seller: sampleUsers.sarah_j,
    timestamp: '3h ago',
  },
];

// Notifications
export const initialNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    sender: sampleUsers.maya_zen,
    text: 'liked your comment in "2026 UI Motion" group chat',
    timestamp: '5m ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'comment',
    sender: sampleUsers.daniel_chen,
    text: 'commented on your photo: "Absolute masterpiece design system!"',
    timestamp: '15m ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'follow',
    sender: sampleUsers.sarah_j,
    text: 'started following you. Check out their premium collection!',
    timestamp: '1h ago',
    read: false,
  },
  {
    id: 'n4',
    type: 'marketplace',
    sender: sampleUsers.alex_rivera,
    text: 'offered $30,000 on your listed 2022 Tesla Model 3',
    timestamp: '4h ago',
    read: true,
  },
  {
    id: 'n5',
    type: 'mention',
    sender: sampleUsers.julian_thorne,
    text: 'mentioned you in a post about futuristic dynamic typography layers',
    timestamp: '1d ago',
    read: true,
  },
];
